version: "3"
services:
  warehouse:
    build: .
    ports:
      - '8085:8085'
    restart: unless-stopped
    depends_on:
      - db
    environment:
      spring.datasource.url: jdbc:postgresql://localhost:5432/MyWarehouse
      spring.datasource.username: postgres
      spring.datasource.password: 1234
  db:
    container_name: db
    image: postgres
    environment:
       POSTGRES_PASSWORD: 1234
       POSTGRES_USER: postgres
       POSTGRES_DB: MyWarehouse
    ports:
      - '5432:5432'









